server:
  port: 8087
spring:
  data:
    mongodb:
#      uri: mongodb://mongodbservice:27017/notify_db
       Use the uri: mongodb://localhost:27017/notify_db
  application:
    name: user-notification-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka # use http://localhost:8761/eureka when running on local system
    fetchRegistry: true
    registerWithEureka: true
#  instance:
#    hostname: localhost
#  instance:
#    preferIpAddress : true